- hosts: tag_AutomatedML_cluster

  tasks:
    - name: Update apt packages
      # shell: apt-get update
      become: true
      apt:
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install python3.5
      become: true
      apt:
        name: python3.5
        state: present

    - name: install setup tools
      become: true
      apt:
        name: python-setuptools
        state: present

    - name: install python3-pip
      become: true
      apt:
        name: python3-pip
        state: present

    - name: install numpy
      pip:
        name: numpy
        state: present
        executable: pip3

    - name: install scipy
      pip:
        name: scipy
        state: present
        executable: pip3

    - name: install scikit-learn
      pip:
        name: scikit-learn
        state: present
        executable: pip3

    - name: install pillow
      pip:
        name: pillow
        state: present
        executable: pip3

    - name: install h5py
      pip:
        name: h5py
        state: present
        executable: pip3

    - name: install tensorflow
      pip:
        name: tensorflow
        state: present
        executable: pip3

    - name: install keras
      pip:
        name: keras
        state: present
        executable: pip3
